---
driver:
  name: docker

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltproject.io
  salt_version: latest
  require_chef: false
  log_level: info
  formula: alloy

platforms:
  - name: ubuntu-24.04
    driver:
      image: ubuntu:24.04
      platform: ubuntu
  - name: ubuntu-22.04
    driver:
      image: ubuntu:22.04
      platform: ubuntu
  - name: debian-12
    driver:
      image: debian:12
      platform: debian
  - name: rockylinux-9
    driver:
      image: rockylinux:9
      platform: rhel
  - name: opensuse-leap-15
    driver:
      image: opensuse/leap:15
      platform: opensuse

suites:
  - name: default
    provisioner:
      state_top:
        base:
          '*':
            - alloy
      pillar_from_files:
        - test/pillar.sls
    verifier:
      inspec_tests:
        - test/integration/default/inspec
